# About
baseurl: "http://kokkos.org/"
title: "Kokkos"
languagecode: "en-us"
# Website menu
languages:
  en:
    menu:
      main:
      - identifier: "home"
        name: "Home"
        url: "/"
        weight: 10
      - identifier: "about"
        name: "About"
        url: "/about/"
        weight: 20
      - identifier: "repositories"
        name: "Repositories"
        url: "/repositories/"
        weight: 30
      - identifier: "documentation"
        name: "Documentation"
        url: "/documentation/"
        weight: 40
      - identifier: "blog"
        name: "Blog"
        url: "/blog/"
        weight: 50
      - identifier: "outreach"
        name: "Outreach"
        url: "/outreach/"
        weight: 60
      - identifier: "community"
        name: "Community"
        url: "/community/"
        weight: 70
      - identifier: "contact"
        name: "Contact"
        url: "/contact/"
        weight: 80
      - identifier: "search"
        name: "Search"
        url: "/search/"
        weight: 90
    weight: 9
# Path to take static files
staticDir:
  - assets
# Theme import
module:
  imports:
  - path: "github.com/willfaught/paige"
# Config search
params:
  search: true
outputs:
  home:
  - "HTML"
  - "JSON"
  - "RSS"
# Enable some html balise
markup:
  goldmark:
    renderer:
      unsafe: true
